### ISSUE TITLE
KeyPlacement not Following Column order

### ISSUE THREAD

**Issue by PabloOyarzo** [adamws/kicad-kbplacer#21]
**Describe the bug**
Tried different layout export from Keyboard Layout Editor and it doesn't follow the column order 

**Additional context**
Heres kbplacer.log
[kbplacer.log](https://github.com/adamws/kicad-kbplacer/files/14143190/kbplacer.log)

**Screenshots**
![Screenshot_13](https://github.com/adamws/kicad-kbplacer/assets/8781283/bc75eeec-1049-412f-8ec1-741149f17ac2)
![Screenshot_14](https://github.com/adamws/kicad-kbplacer/assets/8781283/b862082c-4542-4f77-912c-d1736ceb263d)
![Screenshot_15](https://github.com/adamws/kicad-kbplacer/assets/8781283/da090013-7e99-4558-8c7e-8db1351e1dd3)
![image](https://github.com/adamws/kicad-kbplacer/assets/8781283/0420dd68-84b9-451c-93b8-dc534d8b0906)

**KiCad version info**
```
Application: KiCad PCB Editor x64 on x64

Version: 7.0.7, release build

Libraries:
	wxWidgets 3.2.2
	FreeType 2.12.1
	HarfBuzz 6.0.0
	FontConfig 2.14.1
	libcurl/7.88.1-DEV Schannel zlib/1.2.13

Platform: Windows 10 (build 19045), 64-bit edition, 64 bit, Little endian, wxMSW

Build Info:
	Date: Aug 14 2023 02:42:39
	wxWidgets: 3.2.2 (wchar_t,wx containers)
	Boost: 1.81.0
	OCC: 7.7.1
	Curl: 7.88.1-DEV
	ngspice: 40
	Compiler: Visual C++ 1936 without C++ ABI

Build settings:
	KICAD_SPICE=ON

```

**Comment by adamws** [comment]
`kblacer` places switches in keyboard-layout-editor order which is topmost leftmost, see example:
![image](https://github.com/adamws/kicad-kbplacer/assets/12676586/daf42db6-a940-4d00-8188-9460b855080d)
which is bit counterintuitive for ergo layouts.

I don't have clean solution for that yet.
1) for via-annotated layouts I could sort by labels
2) I could add option to sort by net-list (but that wouldn't work in all cases, in your example you would need to change column orders)

anyway, none of the above are there yet and for now the easiest fix is to rename switches on schematic.

**Comment by adamws** [comment]
you could also modify schematic a bit so the switches placement mimics the physical placement and re-run annotate:
![image](https://github.com/adamws/kicad-kbplacer/assets/12676586/b6b51d14-4930-4dff-b2e0-be68c8eda7cb)

**Comment by PabloOyarzo** [comment]
> alternatively, swap (select two and shift+S) switches on PCB and re-run plugin without layout file and diode placement enabled

This would do the trick for now thanks. 

---

Important to point out that with https://keyboard-tools.xyz/ with the following settings can get  the closest to the result I was looking for. But I had to change the name prefix afterwards. 

![image](https://github.com/adamws/kicad-kbplacer/assets/8781283/64b90054-52f8-4a00-bc9f-12ff2973779b)
![image](https://github.com/adamws/kicad-kbplacer/assets/8781283/780dd93e-dd51-4dd4-8276-82a4f5077718)
