### ISSUE TITLE
How can i place WS2812B LED's?

### ISSUE THREAD

**Issue by SnappierSoap318** [adamws/kicad-kbplacer#28]
How can i add WS2812b's which have a diode annotation?

**Comment by adamws** [comment]
easiest option:
use different annotation for LEDs
![image](https://github.com/adamws/kicad-kbplacer/assets/12676586/b8493ebd-0ae1-4e79-9569-87a7218e1896)
![image](https://github.com/adamws/kicad-kbplacer/assets/12676586/892d44b2-1ab3-4cd3-9af7-cdfed7304b33)

If both key matrix diodes and LEDs use same annotation there is an workaround (make backup first):
- clear annotations
- select LEDs on schematic, run annotation on selection - we want matching numbers between LEDs and switches
- annotate remaining symbols, use 'keep existing annotations'
you should have something like this:
![image](https://github.com/adamws/kicad-kbplacer/assets/12676586/5dd6e94a-b531-496d-be64-2e506f147f04)
- update PCB
- run plugin in two stages:
  - first: (note that diode placement option is unticked)
    ![image](https://github.com/adamws/kicad-kbplacer/assets/12676586/1b5b68aa-d5cd-48e7-935f-cb30eb76deb5)
    it should result in something like this:
    ![image](https://github.com/adamws/kicad-kbplacer/assets/12676586/3947d1e8-30da-4fb8-a055-c8bab1c3c6dd)
  - second (note that layout file is empty - we do not want to move switches anymore, also additional elements list is empty): 
    ![image](https://github.com/adamws/kicad-kbplacer/assets/12676586/2abc1423-f4d5-4c11-8746-9b9981735287)
    should result in something like this:
    ![image](https://github.com/adamws/kicad-kbplacer/assets/12676586/1ed89bb9-7c10-487d-a410-a5af1fc0948c)
- go back to schematic, clear annotations, re-annotate (or revert to previous saved state)
  - use scope and numbering settings in annotation window
- update PCB
  ![image](https://github.com/adamws/kicad-kbplacer/assets/12676586/af8abb93-8700-436a-83d5-dd912f7ef531)

**Comment by SnappierSoap318** [comment]
Thanks for the detailed explanation, I did it the extra hard way, i off-setted the numbers variable in `place_switch_elements` in `key_placer.py` which worked much better than i expected
