### ISSUE TITLE
Place additional components per-switch

### ISSUE THREAD

**Issue by cgarcia2097** [adamws/kicad-kbplacer#3]
[My older codebase](https://github.com/cgarcia2097/kle-placement-router), that has fallen in disrepair, is able to place components other than diodes around the switch. Would you be able to implement that feature in this plugin?

**Comment by adamws** [comment]
you can do it already. Run plugin twice, for second run place first component next to switch, check `Use first switch-diode pair as reference for relative position` and modify `Diode annotation format string` to match new components. This way your other components will be handled just like diodes.
Dedicated interface for this (which would work in single plugin run) might be added in some future release but it is not on top of my priority list.

**Comment by cgarcia2097** [comment]
Understood. That being said, are you accepting pull requests? I could try patching it in.

**Comment by ReFil** [comment]
This would be a really handy feature for placing per switch LEDs alongside switch and diode

**Comment by adamws** [comment]
> This would be a really handy feature for placing per switch LEDs alongside switch and diode

This feature will be part of next release and it currently developed on https://github.com/adamws/kicad-kbplacer/tree/place-additional-elements branch.
