### ISSUE TITLE
[Feature] Add duplex matrix support

### ISSUE THREAD

**Issue by newsve** [adamws/kicad-kbplacer#34]
Which basically means that diodes' direction need be switched for every other column, this is great for low-count-GPIO-MCUs, e.g. the CH552, check out more about the duplex matrix here: 

- In the context of the FAK firmware: https://github.com/semickolon/fak?tab=readme-ov-file#duplex-matrix-support
- Deep dive into the actual matrix design: https://kbd.news/The-Japanese-duplex-matrix-1391.html

**Comment by adamws** [comment]
Added `Automatically adjust orientation` option to diode settings which should cover most Japanese duplex matrix scenarios:
https://github.com/adamws/kicad-kbplacer/tree/master?tab=readme-ov-file#diode-automatic-orientation-adjustment

**Comment by newsve** [comment]
You are amazing, thanks so much! Shall we close this issue then?
