### ISSUE TITLE
Deprecated python list calls

### ISSUE THREAD

**Issue by ReFil** [adamws/kicad-kbplacer#4]
Python 3.8.10 Kicad Version: 7.0.2-6a45011f42~172~ubuntu20.04.1, release build

The version of the plugin that can be downloaded from the plugin editor will not run by default as the list[item] calls used in board_modifier.py and key_placer.py are deprecated, causing an error and the plugin to fail to import. A solution was add `from __future__ import annotations` at the beginning of both of these files and then the plugin shows up on the toolbar and in the external plugins menu

**Comment by adamws** [comment]
Thanks for reporting. Plugin was not tested on ubuntu 20.04 (with python3.8)
Fix delivered to master and will be a part of v0.5 release
