### ISSUE TITLE
Track generation doesn't respect default/netclass width

### ISSUE THREAD

**Issue by robotfishe** [adamws/kicad-kbplacer#40]
When I leave the "route with switches" diode option or "route rows and columns" board option selected, the tracks that are generated are always 0.25mm wide, even with default netclass set to a different value in both schematic and pcb editor. If there's a way to change the width value in the plugin I can't find it. Could the plugin be updated to pull the appropriate netclass value or the current value of the track tool width selector?

**KiCad version info**
```
Application: KiCad Schematic Editor x64 on x64

Version: 7.0.9, release build

Libraries:
	wxWidgets 3.2.3
	FreeType 2.12.1
	HarfBuzz 8.2.1
	FontConfig 2.14.2
	libcurl/8.4.0-DEV Schannel zlib/1.3

Platform: Windows 11 (build 22631), 64-bit edition, 64 bit, Little endian, wxMSW

Build Info:
	Date: Nov  5 2023 19:26:40
	wxWidgets: 3.2.3 (wchar_t,wx containers)
	Boost: 1.83.0
	OCC: 7.7.1
	Curl: 8.4.0-DEV
	ngspice: 41
	Compiler: Visual C++ 1936 without C++ ABI

Build settings:
	KICAD_SPICE=ON

```

**Comment by adamws** [comment]
Track width is currently hardcoded. Pulling width from netclass or exposing control via gui/cli is a valid improvement idea.
For now you must edit code: https://github.com/adamws/kicad-kbplacer/blob/8aa576c8fc1bec9890b0dca897f1b03837f5664e/kbplacer/board_modifier.py#L386
