### ISSUE TITLE
Exception on python  action plugin code

### ISSUE THREAD

**Issue by Pimentoso** [adamws/kicad-kbplacer#5]
Hi,

trying to run the keyboard placer plugin but I'm getting this error.
<img width="632" alt="Screenshot 2023-06-16 at 22 04 35" src="https://github.com/adamws/kicad-kbplacer/assets/6085909/ad769449-5ade-4fef-b58e-3b5a7955c066">

Here is the keyboard json, converted from KLE using one of the tools mentioned in the guide.
https://pastebin.com/s0VmUtqL

Kicad info 
```
Application: KiCad PCB Editor arm64 on arm64

Version: 7.0.5-0, release build

Libraries:
	wxWidgets 3.2.2
	FreeType 2.12.1
	HarfBuzz 5.3.1
	FontConfig 2.14.0
	libcurl/7.88.1 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.11 nghttp2/1.51.0

Platform: macOS Ventura Version 13.4 (Build 22F66), 64 bit, Little endian, wxMac

Build Info:
	Date: May 26 2023 08:14:40
	wxWidgets: 3.2.2 (wchar_t,wx containers)
	Boost: 1.80.0
	OCC: 7.6.3
	Curl: 7.77.0
	ngspice: 38
	Compiler: Clang 13.0.0 with C++ ABI 1002

Build settings:
	KICAD_SPICE=ON
```

**Comment by adamws** [comment]
does it work when `Add Tracks` options unchecked?
which switch footprints do you use? can you share `.kicad_pcb` file and `kbplacer.log` file?

**Comment by Pimentoso** [comment]
Thanks @adamws by looking at the kbplacer.log
```
22:04:27 com_github_adamws_kicad-kbplacer.kbplacer_plugin_action 35: Searching for SW1 footprint
```
I'm afraid it's looking for a symbol named SW1 while in my schema it's MX1. See attached. I probably have to rename my symbols

Here are the files you requested
https://files.catbox.moe/7s5wuq.kicad_pcb
https://files.catbox.moe/k3uop5.log

**Comment by adamws** [comment]
No need to rename footprints, you can change default switch annotation from `SW{}` to `MX{}`
![image](https://github.com/adamws/kicad-kbplacer/assets/12676586/e328a85b-214a-4e6b-9dc9-dcbc2a58d777)
I've run plugin with yours board and it looks like number of switches does not match layout file - `Cannot find footprint MX54`
![image](https://github.com/adamws/kicad-kbplacer/assets/12676586/afc29a11-3285-4500-915c-b6e07d6efa4c)
This will be the result: 
![image](https://github.com/adamws/kicad-kbplacer/assets/12676586/21b7505d-31df-446b-9691-c1316df1aa89)
can you share initial json layout file (not internal form)?

**Comment by Pimentoso** [comment]
Thanks @adamws for the hint, I can take it from here and do some tests. The error is probably because the board has a rotary encoder which has a diode, and the Dxx/MXxx naming is not consistent for the last few switches (the arrows at the bottom right)
I will let you know. Thanks again
